substitutions:
  hostname: test-esp32s3
  wifi_update_interval: "5s"

esphome:
  name: bathroom-sensor

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

# Setup i2c bus for light sensor to work
i2c:
  sda: 14
  scl: 13
  scan: true
  id: bus_a

sensor:
  - platform: wifi_signal
    name: $hostname rssi
    update_interval: $wifi_update_interval
  - platform: ltr390
    uv:
      name: "UV Index"
    light:
      name: "Light Sensor"
    ambient_light:
      name: "Ambient Light Sensor"
    update_interval: 2s

#binary_sensor:
#  - platform: gpio
#    pin: 14
#    name: "PIR Sensor"
#    device_class: motion
#    filters:
#      - delayed_off: 90s

