esphome:
  name: lavatory

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf 

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

i2c:
  sda: 14
  scl: 13
  scan: true
  id: bus_a

sensor:
  - platform: ltr390
    uv:
      name: "UV Index"
    light:
      name: "Light Sensor"
    ambient_light:
      name: "Ambient Light Sensor"
    update_interval: 1.5s

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

